// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/api/storagemigration/v1

package v1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// StorageVersionMigration represents a migration of stored data to the latest
// storage version.
// +k8s:supportsSubresource="/status"
#StorageVersionMigration: {
	TypeMeta: metav1.#TypeMeta

	// Standard object metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	metadata?: metav1.#ObjectMeta @go(ObjectMeta) @protobuf(1,bytes,opt)

	// Specification of the migration.
	// +optional
	spec?: #StorageVersionMigrationSpec @go(Spec) @protobuf(2,bytes,opt)

	// Status of the migration.
	// +optional
	status?: #StorageVersionMigrationStatus @go(Status) @protobuf(3,bytes,opt)
}

// Spec of the storage version migration.
#StorageVersionMigrationSpec: {
	// The resource that is being migrated. The migrator sends requests to
	// the endpoint serving the resource.
	// Immutable.
	resource: metav1.#GroupResource @go(Resource) @protobuf(1,bytes,opt)
}

#MigrationConditionType: string // #enumMigrationConditionType

#enumMigrationConditionType:
	#MigrationRunning |
	#MigrationSucceeded |
	#MigrationFailed

// Indicates that the migration is running.
#MigrationRunning: #MigrationConditionType & "Running"

// Indicates that the migration has completed successfully.
#MigrationSucceeded: #MigrationConditionType & "Succeeded"

// Indicates that the migration has failed.
#MigrationFailed: #MigrationConditionType & "Failed"

// Status of the storage version migration.
#StorageVersionMigrationStatus: {
	// The latest available observations of the migration's current state.
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	// +optional
	// +k8s:alpha(since: "1.37")=+k8s:optional
	// +k8s:alpha(since: "1.37")=+k8s:listType=map
	// +k8s:alpha(since: "1.37")=+k8s:listMapKey=type
	conditions?: [...metav1.#Condition] @go(Conditions,[]metav1.Condition) @protobuf(1,bytes,rep)

	// ResourceVersion to compare with the GC cache for performing the migration.
	// This is the current resource version of given group, version and resource when
	// kube-controller-manager first observes this StorageVersionMigration resource.
	resourceVersion?: string @go(ResourceVersion) @protobuf(2,bytes,opt)
}

// StorageVersionMigrationList is a collection of storage version migrations.
#StorageVersionMigrationList: {
	TypeMeta: metav1.#TypeMeta

	// Standard list metadata
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	metadata?: metav1.#ListMeta @go(ListMeta) @protobuf(1,bytes,opt)

	// Items is the list of StorageVersionMigration
	items: [...#StorageVersionMigration] @go(Items,[]StorageVersionMigration) @protobuf(2,bytes,rep)
}
