name: generate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  latest-k8s:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
          cache: false
      - name: Setup CUE
        uses: cue-lang/setup-cue@1713281ae501e533ff06108005dffeab9e2e5203 # v1.0.0
        with:
          version: v0.6.0
      - name: Setup kubectl
        uses: azure/setup-kubectl@901a10e89ea615cf61f57ac05cecdf23e7de06d8 # v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Generate
        id: gen
        run: |
          go env
          version=$(kubectl version --client -ojson | jq -r .clientVersion.gitVersion)
          pkg_version=${version/v1/v0}
          ./scripts/schema-generator.sh $pkg_version
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: Add Kubernetes ${{ steps.gen.outputs.version }} schemas
          branch: k8s-${{ steps.gen.outputs.version }}
          title: Add Kubernetes ${{ steps.gen.outputs.version }} schemas
          body: Kubernetes ${{ steps.gen.outputs.version }} schemas
